---
title: "R Notebook"
output: html_notebook
---



```{r}
# load library and dataset
library(readr)
library(ggplot2)
library(ggthemes)
curr_complete_dataset <- read_csv("/Users/xiaopaoshangtiantang/CaseStudy_1/Data/curr_complete_dataset.csv")# change the address
```


# Draw a plot about the number of patients in SNF every month in 2019

```{r}

library(ggplot2)

library(ggthemes)
x = c(1,2,3,4,5,6,7,8,9,10,11,12)
y = as.vector(unlist(curr_complete_dataset[1,2:13])) # curr_complete_dataset[i,2:13] change i to get relative row


df <- data.frame(Month = x, Number = y)


ggplot(data=df, aes(x=Month, y=Number,group = factor(1))) +
  geom_bar(stat="identity", fill="steelblue")+
  geom_text(aes(label=Number), vjust=-0.3, size=3.5)+ scale_x_continuous(breaks=seq(1, 12, 1))+
  theme_minimal()+labs(y = "Number  of  Patients") + scale_y_continuous(breaks=seq(1, 1000, 5))


```



```{r}
# load dataset
library(readr)
curr_CT1_CT2_eachmonth <- read_csv("/Users/xiaopaoshangtiantang/CaseStudy_1/Data/curr_CT1_CT2_eachmonth.csv")

curr_CT1_CT2_eachmonth
```

# Draw a plot about the number of different CT type patients in SNF every month in 2019

```{r}
Name = paste("PID",as.character(curr_CT1_CT2_eachmonth[2,1]),sep='')#curr_CT1_CT2_eachmonth[i,1] change i to get relative row
CT1 <- curr_CT1_CT2_eachmonth[2,2:13]# curr_CT1_CT2_eachmontht[i,2:13] change i to get relative row
CT2 <- curr_CT1_CT2_eachmonth[2,14:25] #curr_CT1_CT2_eachmonth[2,14:25] change i to get relative row

X<-rep(1,24)
count1 = 1
count2 = 1
for(i in 1:24){ 
if(i%%2!=0){
X[i]<-as.double(CT1[count1])
count1 = count1 + 1
} 
else{
X[i]<- as.double(CT2[count2])
count2 = count2 + 1
}
}


Month <- factor(rep(1:12, each = 2))
CT_type <- rep(c('CT1','CT2'),times = 12)
set.seed(1234)
Number <- X
df <- data.frame(x = Month, y = Number, CT_type = CT_type)
ggplot(data = df, mapping = aes(x = Month, y = Number, fill = CT_type)) + geom_bar(stat = 'identity', position = 'dodge')+theme_minimal() + labs(title = Name,y = "Number  of  Patients")+ theme(legend.title = element_blank())




```

